-- Seed: Techniques (~120 techniques)
-- Source: docs/taxonomy.md Layer 3
-- Requires subtopics.sql to have run first

INSERT INTO techniques (code, name, cognitive_load, primary_subtopic_id)
SELECT t.code, t.name, t.cognitive_load, s.id
FROM (VALUES
  -- ALG Foundational
  ('T-SPECPROD',   'Special Products & Factorisation Patterns',          'foundational', 'ALG-MAN'),
  ('T-DIFFSQ',     'Difference of Squares / Cubes / Sophie Germain',     'foundational', 'ALG-MAN'),
  ('T-ALGFRAC',    'Algebraic Fractions & Rationalisation',              'foundational', 'ALG-MAN'),
  ('T-SUBST',      'Strategic Substitution (let u = …)',                 'foundational', 'ALG-MAN'),
  ('T-QUADFORM',   'Quadratic Formula, Discriminant & Sign Analysis',    'foundational', 'ALG-EQN'),
  ('T-PARAMSOLVE', 'Equations with Parameters',                          'foundational', 'ALG-EQN'),
  ('T-WORDMODEL',  'Algebraic Modelling of Word Problems',               'foundational', 'ALG-EQN'),
  ('T-SIGNINEQ',   'Sign Analysis & Comparison by Subtraction',          'foundational', 'ALG-BAS-INQ'),
  ('T-ABSVAL',     'Absolute Value Reasoning',                           'foundational', 'ALG-BAS-INQ'),
  ('T-TRIVBOUND',  'Trivial Bounds (squares ≥ 0, |x| ≥ 0)',             'foundational', 'ALG-BAS-INQ'),
  ('T-TELESCOPE',  'Telescoping Sums & Products',                        'foundational', 'ALG-PAT'),
  ('T-GROUP',      'Grouping & Pairing Tricks',                          'foundational', 'ALG-PAT'),
  ('T-APGP',       'AP / GP Formulas & Properties',                      'foundational', 'ALG-PROG'),
  ('T-SIGMA',      'Sigma Notation & Finite Sum Formulas',               'foundational', 'ALG-PROG'),
  -- ALG Intermediate
  ('T-VIETA',      'Vieta''s Formulas',                                  'intermediate', 'ALG-POL'),
  ('T-FACREM',     'Factor & Remainder Theorem',                         'intermediate', 'ALG-POL'),
  ('T-SYMPOLY',    'Symmetric Polynomials & Newton''s Identities',       'intermediate', 'ALG-POL'),
  ('T-ROOTBOUND',  'Root Bounding & Irreducibility',                     'intermediate', 'ALG-POL'),
  ('T-AMGM',       'AM-GM and Weighted AM-GM',                           'intermediate', 'ALG-INQ'),
  ('T-CS',         'Cauchy-Schwarz (direct & Engel/Titu form)',          'intermediate', 'ALG-INQ'),
  ('T-REARRANGE',  'Rearrangement Inequality',                           'intermediate', 'ALG-INQ'),
  ('T-CHEBY',      'Chebyshev Sum Inequality',                           'intermediate', 'ALG-INQ'),
  ('T-POWERMEAN',  'Power Mean Inequality',                              'intermediate', 'ALG-INQ'),
  ('T-SYMSUB',     'Symmetric Substitution (s, p, q)',                   'intermediate', 'ALG-SYS'),
  ('T-CHARACT',    'Characteristic Equation for Recurrences',            'intermediate', 'ALG-SEQ'),
  ('T-INDUCTION',  'Mathematical Induction (weak & strong)',             'intermediate', 'ALG-IND'),
  ('T-ABEL',       'Abel Summation & Summation by Parts',                'intermediate', 'ALG-SUM'),
  -- ALG Advanced
  ('T-CAUCHY-FEQ', 'Cauchy-type Functional Equations',                   'advanced',     'ALG-FEQ'),
  ('T-INJSURJ',    'Injectivity / Surjectivity Deduction',               'advanced',     'ALG-FEQ'),
  ('T-FIXEDPT',    'Fixed-Point & Periodicity in FEs',                   'advanced',     'ALG-FEQ'),
  ('T-SCHUR',      'Schur''s Inequality',                                'advanced',     'ALG-ADV-INQ'),
  ('T-SOS',        'Sum of Squares Decomposition',                       'advanced',     'ALG-ADV-INQ'),
  ('T-JENSEN',     'Jensen''s Inequality & Convexity',                   'advanced',     'ALG-ADV-INQ'),
  ('T-SMOOTH',     'Smoothing / Mixing Variables',                       'advanced',     'ALG-ADV-INQ'),
  ('T-TANGENT',    'Tangent Line Trick',                                 'advanced',     'ALG-ADV-INQ'),
  ('T-MUIRHEAD',   'Muirhead''s Inequality & Majorisation',              'advanced',     'ALG-ADV-INQ'),
  ('T-UVWXYZ',     'uvw / pqr Substitution Method',                      'elite',        'ALG-ADV-INQ'),
  -- NT Foundational
  ('T-PARITY-NT',  'Parity Arguments in Number Theory',                  'foundational', 'NT-BAS'),
  ('T-LASTDIGIT',  'Last-Digit & Digit-Sum Analysis',                    'foundational', 'NT-BAS'),
  ('T-DIVRULES',   'Divisibility Rules (2, 3, 4, 5, 9, 11)',             'foundational', 'NT-BAS'),
  ('T-DIVALGO',    'Division Algorithm & Remainders',                    'foundational', 'NT-DIV'),
  ('T-EUCLID',     'Euclidean Algorithm (basic GCD computation)',         'foundational', 'NT-DIV'),
  ('T-GCDLCM',     'GCD/LCM via Prime Factorisation',                   'foundational', 'NT-DIV'),
  ('T-FTA',        'Fundamental Theorem of Arithmetic',                  'foundational', 'NT-PRM-BAS'),
  ('T-DIVCOUNT',   'Counting Divisors from Factorisation',               'foundational', 'NT-PRM-BAS'),
  ('T-CONGBASIC',  'Congruence Notation & Residue Arithmetic',           'foundational', 'NT-MOD-BAS'),
  ('T-LINCONG',    'Solving Simple Linear Congruences',                  'foundational', 'NT-MOD-BAS'),
  ('T-LINDIO',     'Linear Diophantine Equations (ax + by = c)',         'foundational', 'NT-DIO-BAS'),
  ('T-SMALLDIO',   'Small Quadratic Diophantines (x² ± y² = n)',         'foundational', 'NT-DIO-BAS'),
  -- NT Intermediate
  ('T-FLT',        'Fermat''s Little Theorem',                           'intermediate', 'NT-MOD'),
  ('T-EULER',      'Euler''s Theorem & Totient Function',                'intermediate', 'NT-MOD'),
  ('T-WILSON',     'Wilson''s Theorem',                                  'intermediate', 'NT-MOD'),
  ('T-ORD',        'Order of an Element mod n',                          'intermediate', 'NT-MOD'),
  ('T-CRT',        'Chinese Remainder Theorem',                          'intermediate', 'NT-MOD'),
  ('T-LEGENDRE',   'Legendre''s Formula (v_p(n!))',                      'intermediate', 'NT-PRM'),
  ('T-DESCENT',    'Infinite Descent',                                   'intermediate', 'NT-DIO'),
  ('T-VIETA-JUMP', 'Vieta Jumping (root flipping)',                      'intermediate', 'NT-DIO'),
  ('T-PELLBASIC',  'Pell Equations (basic)',                             'intermediate', 'NT-DIO'),
  ('T-TOTIENT',    'Euler''s Totient Properties & Computation',          'intermediate', 'NT-MUL'),
  ('T-DIVSUMFN',   'Divisor Sum Functions (τ, σ)',                       'intermediate', 'NT-MUL'),
  -- NT Advanced
  ('T-PADIC',      'p-adic Valuations',                                  'advanced',     'NT-VAL'),
  ('T-LTE',        'Lifting the Exponent Lemma',                         'advanced',     'NT-VAL'),
  ('T-HENSEL',     'Hensel''s Lemma (lifting mod p^k)',                  'advanced',     'NT-VAL'),
  ('T-QR',         'Quadratic Residues & Legendre Symbol',               'advanced',     'NT-QR'),
  ('T-QRECIP',     'Quadratic Reciprocity',                              'elite',        'NT-QR'),
  ('T-ZSIG',       'Zsygmondy''s Theorem',                               'elite',        'NT-CON'),
  -- GEO-S Foundational
  ('T-ANGREL',     'Angle Relationships at Parallels',                   'foundational', 'GEO-S-FUN'),
  ('T-CONGCRIT',   'Triangle Congruence Criteria (SSS, SAS, ASA)',       'foundational', 'GEO-S-TRI-BAS'),
  ('T-SIMCRIT',    'Triangle Similarity Criteria (AA, SAS, SSS)',        'foundational', 'GEO-S-TRI-BAS'),
  ('T-PYTHAG',     'Pythagorean Theorem & Converse',                     'foundational', 'GEO-S-TRI-BAS'),
  ('T-NOTABLEPTS', 'Notable Points (centroid, incentre, circumcentre, orthocentre)', 'foundational', 'GEO-S-TRI-BAS'),
  ('T-INSCANG',    'Inscribed Angle Theorem & Corollaries',              'foundational', 'GEO-S-CIR-BAS'),
  ('T-TANGPERP',   'Tangent-Radius Perpendicularity',                    'foundational', 'GEO-S-CIR-BAS'),
  ('T-AREADECOMP', 'Area Decomposition & Ratios',                        'foundational', 'GEO-S-AREA'),
  ('T-DISTMID',    'Distance & Midpoint Formulas',                       'foundational', 'GEO-A-BAS'),
  ('T-SLOPEQ',     'Slope & Line Equations',                             'foundational', 'GEO-A-BAS'),
  ('T-BASICSYM',   'Basic Symmetry (reflection, rotation 90°/180°)',     'foundational', 'GEO-A-TRN-BAS'),
  -- GEO-S Intermediate
  ('T-CEVA',       'Ceva''s Theorem (ratio & trig forms)',               'intermediate', 'GEO-S-TRI'),
  ('T-STEWART',    'Stewart''s Theorem',                                 'intermediate', 'GEO-S-TRI'),
  ('T-ANGBISECT',  'Angle Bisector Theorem',                             'intermediate', 'GEO-S-TRI'),
  ('T-POP',        'Power of a Point',                                   'intermediate', 'GEO-S-CIR'),
  ('T-RADAXIS',    'Radical Axis & Radical Centre',                      'intermediate', 'GEO-S-CIR'),
  ('T-PTOLEMY',    'Ptolemy''s Inequality / Equality',                   'intermediate', 'GEO-S-CIR'),
  ('T-SIMSON',     'Simson Line & Pedal Triangles',                      'intermediate', 'GEO-S-CIR'),
  ('T-ANGCHASE',   'Directed Angle Chasing',                             'intermediate', 'GEO-S-ANG'),
  ('T-MENELAUS',   'Menelaus'' Theorem',                                 'intermediate', 'GEO-S-COL'),
  ('T-SHOELACE',   'Shoelace Formula for Area',                          'intermediate', 'GEO-A-CRD'),
  ('T-HOMOTHETY',  'Homothety & Dilation',                               'intermediate', 'GEO-A-TRN'),
  ('T-SPIRAL',     'Spiral Similarity',                                  'intermediate', 'GEO-A-TRN'),
  ('T-DOTCROSS',   'Dot & Cross Product Proofs',                         'intermediate', 'GEO-A-VEC'),
  -- GEO Advanced
  ('T-PROJECTIVE', 'Projective Methods (cross-ratio, poles/polars)',      'elite',        'GEO-S-PRJ'),
  ('T-HARMONIC',   'Harmonic Division & Conjugates',                     'advanced',     'GEO-S-PRJ'),
  ('T-CPXGEO',     'Complex Number Geometry',                            'advanced',     'GEO-A-CPX'),
  ('T-INV',        'Circle Inversion',                                   'advanced',     'GEO-A-INV'),
  ('T-BARY',       'Barycentric Coordinates (full framework)',            'advanced',     'GEO-A-BARY'),
  -- COMB-E Foundational
  ('T-ADDMULT',    'Addition & Multiplication Principles',               'foundational', 'COMB-E-BAS'),
  ('T-COMPCOUNT',  'Complementary Counting',                             'foundational', 'COMB-E-BAS'),
  ('T-PERMCOMB',   'Permutations & Combinations Formulas',               'foundational', 'COMB-E-PC'),
  ('T-MULTINOMIAL','Arrangements with Identical Objects',                'foundational', 'COMB-E-PC'),
  ('T-BINOMEXP',   'Binomial Expansion & Pascal''s Triangle',            'foundational', 'COMB-E-BIN'),
  ('T-PHP',        'Pigeonhole Principle (basic & generalised)',          'foundational', 'COMB-S-PHP'),
  ('T-HANDSHAKE',  'Handshaking Lemma & Degree Arguments',               'foundational', 'COMB-S-GRP-BAS'),
  ('T-GRAPHCOLOR', 'Graph Colouring (small cases, bipartite)',            'foundational', 'COMB-S-GRP-BAS'),
  -- COMB Intermediate
  ('T-PIE',        'Principle of Inclusion-Exclusion',                   'intermediate', 'COMB-E-CNT'),
  ('T-STARSBAR',   'Stars and Bars',                                     'intermediate', 'COMB-E-CNT'),
  ('T-DERANGE',    'Derangements',                                       'intermediate', 'COMB-E-CNT'),
  ('T-BURNSIDE',   'Burnside''s Lemma',                                  'intermediate', 'COMB-E-CNT'),
  ('T-BIJECTION',  'Bijective Proofs',                                   'intermediate', 'COMB-E-BIJ'),
  ('T-CATALAN',    'Catalan Numbers & Ballot Problem',                   'intermediate', 'COMB-E-BIJ'),
  ('T-COUNTREC',   'Setting Up Counting Recurrences',                    'intermediate', 'COMB-E-REC'),
  ('T-DBLCNT',     'Double Counting',                                    'intermediate', 'COMB-S-GRP'),
  ('T-HALL',       'Hall''s Marriage Theorem',                           'intermediate', 'COMB-S-GRP'),
  ('T-TURAN',      'Turán''s Theorem',                                   'intermediate', 'COMB-S-GRP'),
  ('T-EXTREMAL',   'Extremal Principle (pick the max/min)',               'intermediate', 'COMB-S-EXT'),
  ('T-CONVHULL',   'Convex Hull & Erdős–Szekeres',                       'intermediate', 'COMB-S-CGE'),
  ('T-RAMSEY',     'Small Ramsey Arguments (R(3,3)=6 style)',             'intermediate', 'COMB-S-RAM-BAS'),
  -- COMB Advanced
  ('T-OGF',        'Ordinary Generating Functions',                      'advanced',     'COMB-E-GEN'),
  ('T-EGF',        'Exponential Generating Functions',                   'advanced',     'COMB-E-GEN'),
  ('T-PROBMETHOD', 'Probabilistic Method (Erdős)',                        'advanced',     'COMB-E-PRB'),
  ('T-LINEXP',     'Linearity of Expectation',                           'advanced',     'COMB-E-PRB'),
  ('T-LINALG',     'Linear Algebra in Combinatorics',                    'elite',        'COMB-E-ALG'),
  ('T-GENRAMSEY',  'General Ramsey Bounds & Hales-Jewett',               'advanced',     'COMB-S-RAM'),
  ('T-SUNFLOWER',  'Sunflower Lemma',                                    'advanced',     'COMB-S-SET'),
  ('T-DILWORTH',   'Dilworth''s Theorem & Chain Decomposition',          'advanced',     'COMB-S-ORD'),
  ('T-SPERNER',    'Sperner''s Theorem',                                 'advanced',     'COMB-S-ORD'),
  -- GAME Foundational
  ('T-PARITY',     'Parity Invariant',                                   'foundational', 'GAME-PAR'),
  ('T-COLOURING',  'Checkerboard & Colouring Arguments',                 'foundational', 'GAME-PAR'),
  ('T-TILING',     'Tiling Impossibility via Colouring',                 'foundational', 'GAME-PAR'),
  ('T-NIMBASIC',   'Take-away Game Analysis (small cases, backward induction)', 'foundational', 'GAME-NIMBASIC'),
  ('T-PAIRING',    'Pairing Strategy',                                   'foundational', 'GAME-NIMBASIC'),
  ('T-CONSTRUCT',  'Proof by Explicit Construction',                     'foundational', 'GAME-CON-BAS'),
  -- GAME Intermediate
  ('T-MODINV',     'Modular Invariant',                                  'intermediate', 'GAME-INV'),
  ('T-SUMINV',     'Sum / Product Invariant',                            'intermediate', 'GAME-INV'),
  ('T-ENERGY',     'Energy / Potential Function (monovariant)',           'intermediate', 'GAME-MON'),
  ('T-TERMINATE',  'Termination Proofs via Monovariant',                 'intermediate', 'GAME-MON'),
  ('T-GREEDY',     'Greedy Construction',                                'intermediate', 'GAME-ALG'),
  ('T-SWAP',       'Swapping / Exchange Argument',                       'intermediate', 'GAME-ALG'),
  ('T-STEALSTRAT', 'Strategy Stealing',                                  'intermediate', 'GAME-ALG'),
  -- GAME Advanced
  ('T-NIMVAL',     'Nim-values & Sprague-Grundy Theory',                 'advanced',     'GAME-STR'),
  ('T-COMPGAME',   'Compound Game Decomposition',                        'advanced',     'GAME-STR'),
  ('T-ADVCON',     'Advanced Constructions (multi-constraint, extremal)', 'advanced',     'GAME-CON')
) AS t(code, name, cognitive_load, subtopic_code)
JOIN subtopics s ON s.code = t.subtopic_code
ON CONFLICT (code) DO NOTHING;
